AWSTemplateFormatVersion: 2010-09-09
Description: 'This template deploys a Citrix Server VDA.'

Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Network Configuration
        Parameters:
          - PrivateVDASubnet1
          - PrivateVDASubnet2
      - Label:
          default: Amazon EC2 Configuration
        Parameters:
          - KeyPairName
          - CitrixVDAInstanceType
          - CitrixVDAWindowsServerVersion          
      - Label:
          default: Active Directory Configuration
        Parameters:
          - ADServer1PrivateIP
          - ADServer2PrivateIP
          - DomainDNSName
          - DomainNetBIOSName
          - DomainAdminPassword
          - DomainAdminUser
      - Label:
          default: AWS Quick Start Configuration
        Parameters:
          - QSS3BucketName
          - QSS3KeyPrefix
      - Label:
          default: Citrix Media Installation Location
        Parameters:
          - CitrixInstallS3BucketName
          - CitrixInstallS3KeyPrefix
          - CitrixVDAInstallationFileName
      - Label:
          default: Citrix XenApp/XenDesktop Configuration
        Parameters:
          - CitrixDeliveryController1HostName
          - CitrixDeliveryController2HostName
          - CitrixVDAHostName

    ParameterLabels:
      ADServer1PrivateIP:
        default: Domain Controller 1 Private IP Address
      ADServer2PrivateIP:
        default: Domain Controller 2 Private IP Address   
      CitrixDeliveryController1HostName:
        default: Citrix Delivery Controller 1 Name
      CitrixDeliveryController2HostName:
        default: Citrix Delivery Controller 2 Name           
      CitrixVDAHostName:
        default: Citrix VDA Name        
      CitrixInstallS3BucketName:
        default: Citrix Media Installation S3 Bucket Name
      CitrixInstallS3KeyPrefix:
        default: Citrix Media Installation S3 Key Prefix           
      DomainAdminPassword:
        default: Domain Admin Password
      DomainAdminUser:
        default: Domain Admin User Name
      DomainDNSName:
        default: Domain DNS Name
      DomainNetBIOSName:
        default: Domain NetBIOS Name
      KeyPairName:
        default: Key Pair Name
      PrivateVDASubnet1:
        default: Private Citrix VDA Subnet 1 ID
      PrivateVDASubnet2:
        default: Private Citrix VDA Subnet 2 ID
      QSS3BucketName:
        default: Quick Start S3 Bucket Name
      QSS3KeyPrefix:
        default: Quick Start S3 Key Prefix
      CitrixVDAInstallationFileName:
        default: Citrix VDA Install Media
      CitrixVDAInstanceType:
        default: Citrix Server VDA Instance Type
      CitrixVDAWindowsServerVersion:
        default: Windows Server Version for Citrix Server VDA        

Parameters:
  ADServer1PrivateIP:
    Type: String
  ADServer2PrivateIP:
    Type: String    
  CitrixDeliveryController1HostName:
    Type: String
    Default: CTX-DC1
  CitrixDeliveryController2HostName:
    Type: String
    Default: CTX-DC2  
  CitrixVDAHostName:
    Type: String
    Default: CTX-VDA1      
  CitrixInstallS3BucketName:
    AllowedPattern: '^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$'
    ConstraintDescription: >-
      Citrix Install Media location bucket name can include numbers, lowercase letters, uppercase
      letters, and hyphens (-). It cannot start or end with a hyphen (-).
    Description: >-
      S3 bucket name for the Citrix Install Media assets. This bucket name can include
      numbers, lowercase letters, uppercase letters, and hyphens (-), but should
      not start or end with a hyphen. You can specify your own bucket if you
      copy all of the assets and submodules into it, if you want to override the
      Quick Start behavior for your specific implementation.
    Type: String
  CitrixInstallS3KeyPrefix:
    AllowedPattern: '^[0-9a-zA-Z-/]*$'
    ConstraintDescription: >-
      Citrix Install Media key prefix location can include numbers, lowercase letters, uppercase
      letters, hyphens (-), and forward slash (/).
    Description: >-
      S3 key prefix for the Quick Start assets. Quick Start key prefix can
      include numbers, lowercase letters, uppercase letters, hyphens (-), and
      forward slash (/).
    Type: String         
  DomainDNSName:
    AllowedPattern: '[a-zA-Z0-9\-]+\..+'
    Default: example.com
    Description: >-
      Fully qualified domain name (FQDN) of the forest root domain e.g.
      example.com
    MaxLength: '255'
    MinLength: '2'
    Type: String
  DomainNetBIOSName:
    AllowedPattern: '[a-zA-Z0-9\-]+'
    Default: example
    Description: >-
      NetBIOS name of the domain (up to 15 characters) for users of earlier
      versions of Windows e.g. EXAMPLE
    MaxLength: '15'
    MinLength: '1'
    Type: String
  DomainAdminPassword:
    Type: String
    NoEcho: 'true'    
  DomainAdminUser:
    AllowedPattern: '[a-zA-Z0-9]*'
    Default: admin
    Description: >-
      User name for the account that will be added as Domain Administrator. This
      is separate from the default "Administrator" account. Note: Use admin if using managed AD.
    MaxLength: '25'
    MinLength: '5'
    Type: String
  KeyPairName:
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
    Description: >-
      Name of an existing EC2 KeyPair used to get the Administrator password for
      the instance
    Type: 'AWS::EC2::KeyPair::KeyName'
  PrivateVDASubnet1:
    Type: 'AWS::EC2::Subnet::Id'
    MinLength: '1'
  PrivateVDASubnet2:
    Type: 'AWS::EC2::Subnet::Id'
    MinLength: '1'
  QSS3BucketName:
    AllowedPattern: '^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$'
    ConstraintDescription: >-
      Quick Start bucket name can include numbers, lowercase letters, uppercase
      letters, and hyphens (-). It cannot start or end with a hyphen (-).
    Default: aws-quickstart
    Description: >-
      S3 bucket name for the Quick Start assets. This bucket name can include
      numbers, lowercase letters, uppercase letters, and hyphens (-), but should
      not start or end with a hyphen. You can specify your own bucket if you
      copy all of the assets and submodules into it, if you want to override the
      Quick Start behavior for your specific implementation.
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: '^[0-9a-zA-Z-/]*$'
    ConstraintDescription: >-
      Quick Start key prefix can include numbers, lowercase letters, uppercase
      letters, hyphens (-), and forward slash (/).
    Default: quickstart-citrix-xenappxendesktop/
    Description: >-
      S3 key prefix for the Quick Start assets. Quick Start key prefix can
      include numbers, lowercase letters, uppercase letters, hyphens (-), and
      forward slash (/).
    Type: String  
  CitrixVDAInstallationFileName:
    Type: String
    Description:  File name of the VDA Installation Package    
    Default: VDAServerSetup_7.18.exe
  CitrixVDAInstanceType:
    Default: t2.medium
    Type: String
  CitrixVDASecurityGroup:
    Type: 'AWS::EC2::SecurityGroup::Id'
  CitrixVDAWindowsServerVersion:
    Description: Version of preferred Windows Server for the Citrix Cloud Connectors.
    Type: String
    Default: WS2016FULLBASE
    AllowedValues:
      - WS2012R2
      - WS2016FULLBASE    

Mappings:
  AWSAMIRegionMap:
    AMI:
      WS2012R2: Windows_Server-2012-R2_RTM-English-64Bit-Base-2018.07.11
      WS2016FULLBASE: Windows_Server-2016-English-Full-Base-2018.07.11
    ap-south-1:
        WS2012R2: ami-e013228f
        WS2016FULLBASE: ami-ae1627c1
    eu-west-3:
        WS2012R2: ami-e0b1019d
        WS2016FULLBASE: ami-23b6065e
    eu-west-2:
        WS2012R2: ami-a3b259c4
        WS2016FULLBASE: ami-9bb358fc
    eu-west-1:
        WS2012R2: ami-5ef8ebb4
        WS2016FULLBASE: ami-96e1f27c
    ap-northeast-3:
        WS2012R2: ami-04474e79
        WS2016FULLBASE: ami-88424bf5
    ap-northeast-2:
        WS2012R2: ami-28398d46
        WS2016FULLBASE: ami-07219569
    ap-northeast-1:
        WS2012R2: ami-a73c5e4a
        WS2016FULLBASE: ami-49096ba4
    sa-east-1:
        WS2012R2: ami-fac4e396
        WS2016FULLBASE: ami-36caed5a
    ca-central-1:
        WS2012R2: ami-f334b697
        WS2016FULLBASE: ami-303ebc54
    ap-southeast-1:
        WS2012R2: ami-43e49da9
        WS2016FULLBASE: ami-84e79e6e
    ap-southeast-2:
        WS2012R2: ami-e3862381
        WS2016FULLBASE: ami-d48623b6
    eu-central-1:
        WS2012R2: ami-f7ece81c
        WS2016FULLBASE: ami-6af7f381
    us-east-1:
        WS2012R2: ami-60093e1f
        WS2016FULLBASE: ami-2d360152
    us-east-2:
        WS2012R2: ami-ca2318af
        WS2016FULLBASE: ami-36241f53
    us-west-1:
        WS2012R2: ami-132ac970
        WS2016FULLBASE: ami-d12ecdb2
    us-west-2:
        WS2012R2: ami-490b5831
        WS2016FULLBASE: ami-6d336015


Resources:
  VDA:
    Type: 'AWS::EC2::Instance'
    Metadata:
      'AWS::CloudFormation::Authentication':
        S3AccessCreds:
          type: S3
          roleName: !Ref VDARole
          buckets:
            - !Ref QSS3BucketName
      'AWS::CloudFormation::Init':
        configSets:
          config:
            - "CFNsetup"
            - "QuickStartSetup"
            - "rename"
            - "domainjoin"          
            - "installVDA"
            - "finalize"
        CFNsetup:
          files:
            'c:\cfn\cfn-hup.conf':
              content: !Join 
                - ''
                - - |
                    [main]
                  - stack=
                  - !Ref 'AWS::StackId'
                  - |+

                  - region=
                  - !Ref 'AWS::Region'
                  - |+

            'c:\cfn\hooks.d\cfn-auto-reloader.conf':
              content: !Join 
                - ''
                - - |
                    [cfn-auto-reloader-hook]
                  - |
                    triggers=post.update
                  - >
                    path=Resources.VDA.Metadata.AWS::CloudFormation::Init
                  - 'action=cfn-init.exe -v -s '
                  - !Ref 'AWS::StackId'
                  - ' -r VDA'
                  - ' --region '
                  - !Ref 'AWS::Region'
                  - |+

          commands:
            a-set-execution-policy:
              command: powershell.exe -command Set-ExecutionPolicy RemoteSigned 
              waitAfterCompletion: '0'
        QuickStartSetup:
          files:
            'C:\cfn\scripts\Unzip-Archive.ps1':
              source: !Sub https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}submodules/quickstart-microsoft-utilities/scripts/Unzip-Archive.ps1
              authentication: S3AccessCreds 
            'C:\cfn\modules\AWSQuickStart.zip':
              source: !Sub https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}submodules/quickstart-microsoft-utilities/modules/AWSQuickStart.zip
              authentication: S3AccessCreds           
            'c:\cfn\modules\Citrix.zip':
              source: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}modules/Citrix.zip'
              authentication: S3AccessCreds                     
          commands:
            a-unpack-quickstart-module:
              command: >-
                powershell.exe -Command C:\cfn\scripts\Unzip-Archive.ps1 -Source
                C:\cfn\modules\AWSQuickStart.zip -Destination
                C:\Windows\system32\WindowsPowerShell\v1.0\Modules\
              waitAfterCompletion: '0'
            b-unpack-citrix-module:
              command: >-
                powershell.exe -Command C:\cfn\scripts\Unzip-Archive.ps1 -Source
                C:\cfn\modules\Citrix.zip -Destination
                C:\Windows\system32\WindowsPowerShell\v1.0\Modules\
              waitAfterCompletion: '0'                  
        rename:  
          commands:
            a-execute-powershell-script-RenameComputer:  
              command: !Sub | 
                powershell.exe -Command Rename-Computer -NewName ${CitrixVDAHostName} -Restart
              waitAfterCompletion: 'forever'
        domainjoin:  
          files:
            'c:\cfn\scripts\Set-Dns.ps1':
              source: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}submodules/quickstart-microsoft-utilities/scripts/Set-Dns.ps1'
              authentication: S3AccessCreds              
            'c:\cfn\scripts\Join-Domain.ps1':
              source: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}submodules/quickstart-microsoft-utilities/scripts/Join-Domain.ps1'
              authentication: S3AccessCreds  
          commands:
            a-set-dns:
              command: !Sub |
                powershell.exe c:\cfn\scripts\Set-Dns.ps1 ${ADServer1PrivateIP} ${ADServer2PrivateIP}
              waitAfterCompletion: '30'
            b-join-domain:
              command: !Sub |
                powershell.exe c:\cfn\scripts\Join-Domain.ps1 ${DomainDNSName} ${DomainNetBIOSName}\${DomainAdminUser} '${DomainAdminPassword}'
              waitAfterCompletion: 'forever'
        installVDA:
          files:
            'c:\cfn\scripts\VDAServerSetup.exe':
              source: !Sub 'https://${CitrixInstallS3BucketName}.s3.amazonaws.com/${CitrixInstallS3KeyPrefix}/${CitrixVDAInstallationFileName}'
              authentication: S3AccessCreds
            'C:\cfn\scripts\Prep-VDA.ps1':
              source: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}scripts/Prep-VDA.ps1'
              authentication: S3AccessCreds
            'c:\cfn\scripts\Install-VDA.ps1':
              source: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}scripts/Install-VDA.ps1'
              authentication: S3AccessCreds 
            'c:\cfn\scripts\DisableIEESC.ps1':
              source: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}scripts/DisableIEESC.ps1'
              authentication: S3AccessCreds
            'c:\cfn\scripts\Enable-CredSSP.ps1':
              source: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}submodules/quickstart-microsoft-utilities/scripts/Enable-CredSSP.ps1'
              authentication: S3AccessCreds                  
          commands:
            a-DisableIEESC:
              command: powershell C:\cfn\scripts\DisableIEESC.ps1
              waitAfterCompletion: '0'
            b-Enable-CredSSP:
              command: powershell -command c:\cfn\scripts\Enable-CredSSP.ps1
              waitAfterCompletion: '0'                 
            c-Prep-VDA:
              command: powershell.exe -ExecutionPolicy Unrestricted C:\cfn\scripts\Prep-VDA.ps1
              waitAfterCompletion: '0'
            d-reboot:
              command: powershell.exe -Command Restart-Computer -Force
              waitAfterCompletion: forever                 
            e-Install-VDA: 
              command: !Sub |
                powershell -command C:\cfn\scripts\Install-VDA.ps1 "-VDA_MediaName VDAServerSetup.exe -VDA_MediaLocation c:\cfn\scripts -VDA_Controller1 ${CitrixDeliveryController1HostName} -VDA_Controller2 ${CitrixDeliveryController2HostName} -VDA_DNSDomainName ${DomainDNSName}"
              waitAfterCompletion: '0'
            f-scheduleTargetOSOptimizerOnNextBoot:
              command: reg ADD "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce" /v "CitrixTargetOSOptimizer" /t REG_SZ /d "C:\PROGRA~1\Citrix\PvsVm\TargetOSOptimizer\TargetOSOptimizer.exe /q" /f
              waitAfterCompletion: '0'                         
            g-reboot:
              command: powershell.exe -Command Restart-Computer -Force
              waitAfterCompletion: forever
        finalize:  
          commands:
            z-signal-success:
              command: !Sub |
                cfn-signal.exe -e 0 "${VDAWaitHandle}"
          services:
            windows:
              cfn-hup:
                enabled: 'true'
                ensureRunning: 'true'
                files:
                  - 'c:\cfn\cfn-hup.conf'
                  - 'c:\cfn\hooks.d\cfn-auto-reloader.conf'        
    Properties:
      IamInstanceProfile: !Ref VDAProfile
      InstanceType: !Ref CitrixVDAInstanceType
      ImageId: !FindInMap [ AWSAMIRegionMap, !Ref "AWS::Region", !Ref CitrixVDAWindowsServerVersion ]
      SecurityGroupIds:
        - !Ref CitrixVDASecurityGroup
      KeyName: !Ref KeyPairName
      SubnetId: !Ref PrivateVDASubnet1
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-${CitrixVDAHostName}'
        - Key: App
          Value: Citrix
      UserData: !Base64 
        'Fn::Join':
          - ''
          - - |
              <script>
            - 'cfn-init.exe -v -s '
            - !Ref 'AWS::StackId'
            - ' -r VDA'
            - ' --region '
            - !Ref 'AWS::Region'
            - ' --configsets config'
            - |+
            - </script>

  VDAWaitHandle:
    Type: 'AWS::CloudFormation::WaitConditionHandle'
  VDAWaitCondition:
    Type: 'AWS::CloudFormation::WaitCondition'
    DependsOn: VDA
    Properties:
      Handle: !Ref VDAWaitHandle
      Timeout: '3600'


  VDARole:
    Type: 'AWS::IAM::Role'
    Properties:
      Policies:
        - PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - 's3:GetObject'
                Resource: 
                - !Sub 'arn:aws:s3:::${QSS3BucketName}/${QSS3KeyPrefix}*'
                - !Sub 'arn:aws:s3:::${CitrixInstallS3BucketName}/${CitrixInstallS3KeyPrefix}*'
                Effect: Allow
          PolicyName: aws-quick-start-s3-policy
      Path: /
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Principal:
              Service:
                - ec2.amazonaws.com
            Effect: Allow
        Version: 2012-10-17

  VDAProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Roles:
        - !Ref VDARole
      Path: /


Outputs:
  VDA:
    Description: VDA EC2 instance ID
    Value: !Ref VDA
  VDARole:
    Value: !Ref VDARole
  CitrixVDAHostName:
    Value: !Ref CitrixVDAHostName  