AWSTemplateFormatVersion: '2010-09-09'

Description: IAM User to be used with Citrix MCS and Hosting Configuration as CTX140429.

Resources:
  CitrixUser:
    Type: 'AWS::IAM::User'
    Properties:
      Policies:
        - PolicyName: CitrixXAXDServiceMCS
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
                - ec2:AttachVolume
                - ec2:AuthorizeSecurityGroupEgress
                - ec2:AuthorizeSecurityGroupIngress
                - ec2:CreateImage
                - ec2:CreateNetworkInterface
                - ec2:CreateSecurityGroup
                - ec2:CreateTags
                - ec2:CreateVolume
                - ec2:DeleteNetworkInterface
                - ec2:DeleteSecurityGroup
                - ec2:DeleteSnapshot
                - ec2:DeleteVolume
                - ec2:DeregisterImage
                - ec2:DescribeAccountAttributes
                - ec2:DescribeAvailabilityZones
                - ec2:DescribeImages
                - ec2:DescribeInstances
                - ec2:DescribeNetworkInterfaces
                - ec2:DescribeRegions
                - ec2:DescribeSecurityGroups
                - ec2:DescribeSubnets
                - ec2:DescribeVolumes
                - ec2:DescribeVpcs
                - ec2:DetachVolume
                - ec2:RebootInstances
                - ec2:RevokeSecurityGroupEgress
                - ec2:RevokeSecurityGroupIngress
                - ec2:RunInstances
                - ec2:StartInstances
                - ec2:StopInstances
                - ec2:TerminateInstances
                - s3:CreateBucket
                - s3:DeleteBucket
                - s3:DeleteObject
                - s3:GetObject
                - s3:PutObject
              Resource: "*"
  CitrixAccessKey:
    Type: 'AWS::IAM::AccessKey'
    Properties:
      UserName: !Ref CitrixUser

Outputs:
  AccessKey:
    Value: !Ref CitrixAccessKey
    Description: To be added to Citrix XAXD Hosting Connection within Citrix Cloud
  SecretKey:
    Value: !GetAtt
      - CitrixAccessKey
      - SecretAccessKey
    Description: To be added to Citrix XAXD Hosting Connection within Citrix Cloud
