AWSTemplateFormatVersion: 2010-09-09
Description: 'This template deploys VPC Security Groups for Citrix Cloud Connectors and Citrix VDA'
Parameters:
  VPCID:
    Type: 'AWS::EC2::VPC::Id'
  BastionSecurityGroupID:
    Description: ID of the Bastion Security Group (e.g., sg-7f16e910),
    Type: 'AWS::EC2::SecurityGroup::Id'

Resources:
  CCSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group which allows access to the Cloud Connectors
      VpcId: !Ref VPCID
      SecurityGroupIngress:
        - SourceSecurityGroupId: !Ref BastionSecurityGroupID
          IpProtocol: tcp
          FromPort: 3389
          ToPort: 3389
      Tags:
      - Key: Name
        Value: !Sub '${AWS::StackName}-cc-sg'
      - Key: App
        Value: Citrix

  CCSecurityGroupTCPIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref CCSecurityGroup
      IpProtocol: tcp
      FromPort: '0'
      ToPort: '65535'
      SourceSecurityGroupId: !Ref CCSecurityGroup

  VDASecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group which allows access to the VDA Workers
      VpcId: !Ref VPCID
      SecurityGroupIngress:
        - IpProtocol: TCP
          FromPort: 443
          ToPort: 443
          SourceSecurityGroupId: !Ref CCSecurityGroup
        - IpProtocol: TCP
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref CCSecurityGroup
        - IpProtocol: TCP
          FromPort: 1494
          ToPort: 1494
          SourceSecurityGroupId: !Ref CCSecurityGroup
        - IpProtocol: TCP
          FromPort: 2598
          ToPort: 2598
          SourceSecurityGroupId: !Ref CCSecurityGroup
        - IpProtocol: TCP
          FromPort: 8008
          ToPort: 8008
          SourceSecurityGroupId: !Ref CCSecurityGroup
        - SourceSecurityGroupId: !Ref BastionSecurityGroupID
          IpProtocol: tcp
          FromPort: 3389
          ToPort: 3389
      Tags:
      - Key: Name
        Value: !Sub '${AWS::StackName}-vda-sg'
      - Key: App
        Value: Citrix

  VDASecurityGroupTCPIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref VDASecurityGroup
      IpProtocol: tcp
      FromPort: '0'
      ToPort: '65535'
      SourceSecurityGroupId: !Ref VDASecurityGroup

Outputs:
  CCSecurityGroup:
    Value: !Ref CCSecurityGroup
  VDASecurityGroup:
    Value: !Ref VDASecurityGroup